name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ macos-13, macos-14 ]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BUILD: "cp312-*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_linux:
    runs-on: ubuntu-latest
    name: Build wheels on ${{ matrix.arch }} (${{ matrix.tag }})
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        arch: [ x86_64, i686, aarch64, ppc64le, s390x ]
        tag: [ manylinux, musllinux ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: ${{ matrix.arch }} != 'x86_64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_BUILD: "cp312-${{ matrix.tag }}_*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-linux-${{ matrix.arch }}-${{ matrix.tag }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
