name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  macos:
    name: macOS (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-13, macos-14 ]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_ARCHS_MACOS: "native"
          CIBW_BUILD: "cp312-*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  linux:
    runs-on: ubuntu-latest
    name: Linux (${{ matrix.arch }}, ${{ matrix.tag }})
    strategy:
      matrix:
        arch: [ x86_64, i686, aarch64, ppc64le, s390x ]
        tag: [ manylinux, musllinux ]
        # TODO(charlie): Fails to compile, root cause is unexplored.
        exclude:
          - arch: aarch64
            tag: musllinux

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: ${{ matrix.arch }} != 'x86_64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_BUILD: "cp312-${{ matrix.tag }}_*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-linux-${{ matrix.arch }}-${{ matrix.tag }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
